apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
  - name: client-container
    image: losernerd/cni_benchmark:client
    imagePullPolicy: Always
    command: ["/app/temp.py"]
    envFrom:
    - configMapRef:
        name: bench-config
