apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    dns: benchmark
  namespace: default
spec:
  containers:
  - name: server-container
    image: losernerd/cni_benchmark:server
    imagePullPolicy: Always
    command: ["/app/server.py"]
